"""Catalog of common tabular ML use cases, and a token-free matcher from a plain-language goal to them.

Each entry says what ML task a business goal is: task, target column patterns, unit of prediction,
time handling, primary metric, leakage column patterns, family weight multipliers, usual columns.
Sources and per-use-case notes: docs/USE_CASES.md.

time: "none"       rows are exchangeable; random (stratified) CV.
      "time_split" rows carry a snapshot or event date; split by time (walk_forward), and use purged
                   CV with gap = label window when windows overlap (e.g. churn in the next 90 days).
      "forecast"   one target per series per period; walk_forward CV with gap >= horizon, lag and
                   rolling features shifted by at least the horizon.
families_prior: multipliers on search_space.family_prior (missing family = 1.0); renormalise after.
Column patterns are regexes searched against snake_case column names (SalePrice -> sale_price).
"""
import re
from functools import lru_cache

import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer

S, M, E = "smb", "midmarket_saas", "enterprise"
SEGMENTS = (S, M, E)
TIMES = ("none", "time_split", "forecast")
TASK_KIND = {"binary": "classification", "multiclass": "classification", "regression": "regression"}
_HINT_KIND = {**TASK_KIND, "classification": "classification", "forecast": "regression"}
COL_WEIGHT = 0.25  # column evidence alone can reach at most this score
TASK_MISMATCH = 0.5  # score multiplier when task_hint disagrees with the use case
BEST_PHRASE = 0.7  # text score = 0.7 best single phrasing + 0.3 whole use case document


def _w(alt: str) -> str:
    """Regex: one of the alternatives as a whole snake_case word run."""
    return rf"(^|_)({alt})(_|$)"


def _x(alt: str) -> str:
    """Regex: the whole column name is one of the alternatives."""
    return rf"^({alt})$"


# M5: pooled LightGBM on lags dominated; random forests cannot extrapolate trends; TabICL ignores order.
FORECAST = {"lightgbm": 1.4, "xgboost": 1.1, "catboost": 1.1, "random_forest": 0.8, "mlp": 0.7, "tabicl": 0.6}

USE_CASES: list[dict] = [
    # ---- customer success
    {"id": "customer_churn", "name": "Customer churn (subscription or repeat customers)",
     "domain": "customer_success", "segments": [S, E],
     "question": "Which customers are likely to cancel or stop buying in the next N days?",
     "questions": ["which customers will churn in the next 90 days", "predict customer churn",
                   "who is likely to cancel their subscription", "find customers at risk of leaving",
                   "flag customers likely to stop buying from us", "predict attrition of subscribers",
                   "customer retention risk score", "probability that a customer churns next month"],
     "task": "binary", "time": "time_split", "primary_metric": "roc_auc",
     "metric_why": "Retention teams work a ranked call list, so ranking quality (AUC) matters most; "
                   "use f1_macro when churners are rare and one flag drives action.",
     "unit": "customer at a snapshot date",
     "target_hint": [_x("churn|churned|is_churn|churn_flag|churn_label|exited|attrition|cancelled|canceled|left"),
                     _w("churn|churned|attrition|exited")],
     "leakage_patterns": [_w(r"refund\w*"), _w(r"cancel\w*_(date|reason|at)"), _w(r"churn_(date|reason|at)"),
                          _w(r"termination\w*|terminated_\w+"), _w("close_date|closed_at|account_closed"),
                          _w(r"exit_\w+|winback\w*|win_back"), _w(r"final_(bill|invoice)|disconnect\w*"),
                          _w(r"retention_offer\w*|end_date")],
     "needed_columns": [_w(r"tenure\w*"), _w(r"contract\w*|plan"), _w("monthly_charges|mrr|charges|spend|revenue"),
                        _w("support_tickets|tickets|complaints"), _w(r"last_login\w*|logins?|usage|sessions"),
                        _w("payment_method|billing")],
     "families_prior": {"catboost": 1.2, "lightgbm": 1.1, "logreg": 1.1}},
    {"id": "saas_renewal_churn", "name": "B2B account renewal and logo churn",
     "domain": "customer_success", "segments": [M, E],
     "question": "Which B2B accounts will not renew at their next renewal date?",
     "questions": ["which accounts will not renew their contract", "predict renewal risk for our saas customers",
                   "customer health score for b2b accounts", "which logos are likely to churn before renewal",
                   "forecast gross revenue retention risk by account",
                   "flag at risk accounts for customer success managers",
                   "predict whether a subscription renews at contract end"],
     "task": "binary", "time": "time_split", "primary_metric": "roc_auc",
     "metric_why": "CSMs triage a ranked book of accounts; AUC measures that ranking. Few accounts per "
                   "period, so expect wide confidence intervals.",
     "unit": "account per renewal cycle",
     "target_hint": [_x("renewed|is_renewed|will_renew|renewal|renewal_status|churned|churn|logo_churn"),
                     _w(r"renew\w*|churn\w*")],
     "leakage_patterns": [_w(r"churn_(date|reason)|cancel\w*"), _w(r"downgrade\w*_(date|at)|contraction\w*"),
                          _w(r"renewal_(outcome|result|arr|amount|price)|new_arr|post_renewal\w*"),
                          _w(r"closed_lost\w*|lost_reason"), _w(r"final_invoice|offboard\w*|exit_\w+")],
     "needed_columns": [_w("seats?|licen[cs]es?|seat_utilization"), _w("arr|mrr|acv|contract_value"),
                        _w("dau|mau|wau|active_users|logins?|usage"), _w("tickets?|nps|csat"),
                        _w(r"renewal_date|contract_end\w*|term"), _w(r"csm\w*|qbr\w*|touchpoints?")],
     "families_prior": {"catboost": 1.2, "lightgbm": 1.1, "logreg": 1.2}},
    {"id": "expansion_upsell", "name": "Expansion and upsell propensity",
     "domain": "customer_success", "segments": [M, E],
     "question": "Which existing accounts are ready to buy more seats, a higher plan or an add on?",
     "questions": ["which accounts are likely to upgrade their plan", "predict upsell opportunities",
                   "find customers ready to expand", "expansion propensity score for existing customers",
                   "who will buy more seats next quarter", "predict add on purchases for current accounts"],
     "task": "binary", "time": "time_split", "primary_metric": "roc_auc",
     "metric_why": "Account managers work the top of a ranked list; AUC fits and expansion is a minority class.",
     "unit": "account per quarter",
     "target_hint": [_x("expanded|upgraded|upsell|upsold|expansion|is_expansion|seat_increase"),
                     _w(r"upgrade\w*|upsell\w*|expan\w*")],
     "leakage_patterns": [_w(r"new_(arr|mrr|plan|seats)|upgrade_(date|at)|expansion_(amount|arr|date)"),
                          _w(r"post_(upgrade|expansion)\w*")],
     "needed_columns": [_w("seats?|seat_utilization|licen[cs]es?"), _w(r"usage|active_users|dau|mau|limit\w*"),
                        _w("plan|tier"), _w(r"feature\w*|adoption"), _w("arr|mrr|spend")],
     "families_prior": {"catboost": 1.1, "lightgbm": 1.2}},
    {"id": "support_escalation", "name": "Support ticket escalation",
     "domain": "customer_success", "segments": [M, E],
     "question": "Which new support tickets will escalate or breach the SLA?",
     "questions": ["which tickets will escalate", "predict sla breaches for support tickets",
                   "flag tickets likely to need a manager", "predict which support cases become critical",
                   "early warning for escalated tickets", "which cases will be reopened"],
     "task": "binary", "time": "time_split", "primary_metric": "f1_macro",
     "metric_why": "Escalations are rare and the team acts on a yes or no flag; f1_macro balances missed "
                   "escalations against false alarms.",
     "unit": "ticket at creation or first response",
     "target_hint": [_x("escalated|is_escalated|escalation|sla_breached|breached|reopened"),
                     _w(r"escalat\w*|breach\w*")],
     "leakage_patterns": [_w(r"resolution_\w+|resolved_(at|by|date)|closed_(at|date|by)|time_to_resolve\w*"),
                          _w(r"reopen\w*_count|num_replies|replies|csat\w*|satisfaction\w*"),
                          _w("escalation_(date|at|level|reason)")],
     "needed_columns": [_w("priority|severity"), _w("channel|source"), _w("category|product|queue|topic"),
                        _w("tier|plan|customer_tier|segment"), _w(r"first_response\w*|created\w*"),
                        _w(r"subject\w*|description\w*|text\w*|length")],
     "families_prior": {"lightgbm": 1.2, "catboost": 1.1}},
    {"id": "ticket_resolution_time", "name": "Ticket resolution time",
     "domain": "customer_success", "segments": [M, E],
     "question": "How long will each support ticket take to resolve?",
     "questions": ["how long will this ticket take to resolve", "predict time to resolution for support cases",
                   "estimate handling time per ticket", "predict hours until a case is closed",
                   "forecast resolution time to set customer expectations"],
     "task": "regression", "time": "time_split", "primary_metric": "mae",
     "metric_why": "Durations are right skewed; MAE is robust and targets the median, which is what you "
                   "promise a customer.",
     "unit": "ticket",
     "target_hint": [_x("resolution_hours|resolution_time|time_to_resolve|time_to_resolution|handle_time|"
                        "hours_to_close|days_to_close|ttr"), _w(r"resolution_(time|hours|days)|time_to_\w+")],
     "leakage_patterns": [_w("resolved_(at|date)|closed_(at|date)|close_time"),
                          _w(r"num_replies|replies|touches|reassign\w*|csat\w*|satisfaction\w*"),
                          _w("sla_breached|breached")],
     "needed_columns": [_w("priority|severity"), _w("category|queue|product|topic"), _w("channel"),
                        _w(r"created\w*|opened\w*"), _w("team|agent_group|assignee_group"),
                        _w("backlog|open_tickets|queue_length")],
     "families_prior": {"lightgbm": 1.2, "catboost": 1.1, "ridge": 0.8}},
    {"id": "customer_satisfaction", "name": "Customer satisfaction (NPS or CSAT class)",
     "domain": "customer_success", "segments": [M, E],
     "question": "Will this customer be a promoter, passive or detractor?",
     "questions": ["predict nps category for each customer", "which customers are detractors",
                   "predict customer satisfaction score", "will the customer rate us promoter passive or detractor",
                   "predict csat after a support interaction", "find unhappy customers before the survey"],
     "task": "multiclass", "time": "time_split", "primary_metric": "f1_macro",
     "metric_why": "Classes are uneven (detractors are few); f1_macro makes the model care about every class.",
     "unit": "customer or interaction",
     "target_hint": [_x("nps_category|nps_class|csat|satisfaction|satisfied|rating|promoter_class"),
                     _w(r"nps\w*|csat\w*|satisf\w*")],
     "leakage_patterns": [_w(r"survey_(comment|text|response)\w*|verbatim\w*|follow_up\w*|detractor_flag|nps_score")],
     "needed_columns": [_w("tickets?|complaints?"), _w(r"resolution\w*|wait_time|response_time"),
                        _w("tenure|customer_since"), _w("usage|orders?|spend"), _w(r"delivery\w*|late\w*|delay\w*")],
     "families_prior": {"catboost": 1.2, "lightgbm": 1.1}},
    # ---- sales and marketing
    {"id": "lead_scoring", "name": "Lead scoring", "domain": "sales_marketing", "segments": [S, M, E],
     "question": "Which inbound leads will turn into customers or qualified opportunities?",
     "questions": ["score our inbound leads", "which leads will convert", "predict lead conversion",
                   "rank leads by likelihood to buy", "which prospects should sales call first",
                   "predict which marketing qualified leads become customers", "lead scoring model for the crm"],
     "task": "binary", "time": "time_split", "primary_metric": "roc_auc",
     "metric_why": "Reps call leads in score order, so the metric must reward ranking; AUC does, "
                   "independent of any threshold.",
     "unit": "lead at creation or MQL date",
     "target_hint": [_x("converted|is_converted|won|is_won|became_customer|sql|qualified|conversion"),
                     _w(r"convert\w*|won|qualified")],
     "leakage_patterns": [_w(r"opportunity_(id|amount|stage)|deal_\w+|close_date|closed_(at|date)"),
                          _w(r"converted_(at|date)|won_(at|date)|account_created\w*|customer_id"),
                          _w("sales_stage|lifecycle_stage|lead_status")],
     "needed_columns": [_w(r"lead_source|source|channel|utm\w*"), _w("industry|company_size|employees|revenue"),
                        _w("page_views|visits|sessions|email_opens|clicks"), _w("title|job_title|role|seniority"),
                        _w("country|region|state")],
     "families_prior": {"catboost": 1.2, "lightgbm": 1.1, "logreg": 1.1}},
    {"id": "opportunity_win", "name": "Deal (opportunity) win probability", "domain": "sales_marketing",
     "segments": [M, E], "question": "Which open deals in the pipeline will close as won?",
     "questions": ["which deals will close", "predict opportunity win probability",
                   "forecast which pipeline deals we will win this quarter", "score open opportunities in salesforce",
                   "likelihood that a deal closes won", "predict win or loss for each sales opportunity"],
     "task": "binary", "time": "time_split", "primary_metric": "roc_auc",
     "metric_why": "Pipeline reviews rank and weight deals; AUC checks the ranking, calibration comes from "
                   "the confirm table.",
     "unit": "opportunity at a pipeline snapshot",
     "target_hint": [_x("won|is_won|closed_won|win|outcome|is_closed_won|result"), _w("won|win|closed_won")],
     "leakage_patterns": [_w("close_date|closed_(at|date)|is_closed|days_to_close"),
                          _w("stage|stage_name|forecast_category|probability"),
                          _w("lost_reason|loss_reason|won_reason|win_reason"),
                          _w(r"final_amount|booked\w*|contract_signed\w*")],
     "needed_columns": [_w("amount|deal_size|acv|value"), _w(r"age_days|created\w*|days_open"),
                        _w("industry|segment|region"), _w(r"product\w*|plan"), _w("owner|rep|sales_rep"),
                        _w("meetings?|activities|emails|calls")],
     "families_prior": {"catboost": 1.2, "lightgbm": 1.1}},
    {"id": "campaign_response", "name": "Marketing campaign response", "domain": "sales_marketing",
     "segments": [S, E], "question": "Which customers will respond to this campaign, call or offer?",
     "questions": ["who will respond to our marketing campaign", "predict which customers subscribe after a call",
                   "target the customers most likely to accept the offer", "predict email campaign response",
                   "which contacts will say yes to a term deposit", "propensity to respond to direct mail"],
     "task": "binary", "time": "time_split", "primary_metric": "roc_auc",
     "metric_why": "Budget buys the top k contacts; AUC measures that ordering. Responders are usually "
                   "under 15 percent.",
     "unit": "customer per campaign contact",
     "target_hint": [_x("y|response|responded|subscribed|accepted|accepted_offer|purchased|converted"),
                     _w(r"respon\w*|subscrib\w*|accept\w*")],
     "leakage_patterns": [_x("duration"), _w("call_duration|talk_time"),
                          _w(r"response_(date|at)|redeem\w*|coupon_used|order_id|order_value")],
     "needed_columns": [_w("age|job|occupation|income"), _w("channel|contact"),
                        _w(r"campaign\w*|previous\w*|pdays|poutcome"), _w(r"recency|frequency|monetary|days_since\w*"),
                        _w("segment|tier")],
     "families_prior": {"lightgbm": 1.1, "catboost": 1.1, "logreg": 1.1}},
    {"id": "purchase_propensity", "name": "Purchase propensity (will buy in the next N days)",
     "domain": "sales_marketing", "segments": [S, E],
     "question": "Which customers will make another purchase in the next 30 days?",
     "questions": ["which customers will buy again in the next 30 days", "predict repeat purchase",
                   "propensity to buy score", "who is likely to purchase next month",
                   "predict whether a customer places another order", "find customers ready to reorder"],
     "task": "binary", "time": "time_split", "primary_metric": "roc_auc",
     "metric_why": "Ranks audiences for outreach, so AUC; the label window must start after the feature cutoff.",
     "unit": "customer at a snapshot date",
     "target_hint": [_x(r"purchased|will_buy|repeat|repeat_purchase|bought|reordered|buy_next\w*|purchase_next\w*"),
                     _w(r"purchas\w*|reorder\w*|repeat\w*")],
     "leakage_patterns": [_w(r"next_(order|purchase)_(date|amount|id)|days_to_next\w*|order_count_after\w*")],
     "needed_columns": [_w(r"recency|days_since\w*|last_order\w*"), _w("frequency|orders?|order_count|num_orders"),
                        _w(r"monetary|spend|revenue|aov|avg_order\w*"), _w(r"sessions?|visits?|cart\w*|views?"),
                        _w(r"tenure|signup\w*|first_order\w*")],
     "families_prior": {"lightgbm": 1.2, "catboost": 1.1}},
    {"id": "customer_ltv", "name": "Customer lifetime value", "domain": "sales_marketing", "segments": [S, M, E],
     "question": "How much will each customer spend over the next 12 months?",
     "questions": ["predict customer lifetime value", "how much will each customer spend next year",
                   "estimate clv for new customers", "forecast future revenue per customer",
                   "which customers will be most valuable", "predict 12 month spend per customer"],
     "task": "regression", "time": "time_split", "primary_metric": "mae",
     "metric_why": "Spend is zero inflated and heavy tailed; RMSE chases a few whales, MAE stays robust. "
                   "Use rmse when the planned total (the mean) is what matters.",
     "unit": "customer at a snapshot date",
     "target_hint": [_x(r"ltv|clv|cltv|lifetime_value|future_spend|spend_next\w*|revenue_next\w*"),
                     _w(r"ltv|clv|lifetime_value|future_\w*spend")],
     "leakage_patterns": [_w(r"total_revenue|lifetime_revenue|total_spend|lifetime_spend|orders_after\w*")],
     "needed_columns": [_w(r"first_order\w*|acquisition\w*|signup\w*"), _w("orders?|frequency|num_orders"),
                        _w(r"aov|avg_order\w*|monetary|spend"), _w("channel|source"),
                        _w(r"tenure|recency|days_since\w*")],
     "families_prior": {"lightgbm": 1.2, "catboost": 1.2, "ridge": 0.8, "mlp": 0.8}},
    {"id": "cross_sell", "name": "Cross sell propensity for a product", "domain": "sales_marketing",
     "segments": [S, E],
     "question": "Which existing customers will buy a second product such as insurance, a card or an add on?",
     "questions": ["which customers will buy our other product", "cross sell propensity model",
                   "predict interest in vehicle insurance among health policy holders",
                   "who will accept a credit card offer", "predict which customers take a second product",
                   "find customers to cross sell to"],
     "task": "binary", "time": "time_split", "primary_metric": "roc_auc",
     "metric_why": "Campaigns target the top of a ranked list; AUC, and positives are usually a minority.",
     "unit": "existing customer",
     "target_hint": [_x(r"response|cross_sell|bought_product|accepted|interested|has_product_\w+"),
                     _w(r"cross_sell|respon\w*")],
     "leakage_patterns": [_w(r"(policy|product|account)_(start|open)\w*|new_product_id")],
     "needed_columns": [_w("age|gender|income"), _w("products?|num_products|holdings"),
                        _w("tenure|vintage|customer_since"), _w("channel|region|region_code"),
                        _w("premium|balance|spend")],
     "families_prior": {"lightgbm": 1.2, "catboost": 1.1}},
    {"id": "next_best_offer", "name": "Next best offer (which product next)", "domain": "sales_marketing",
     "segments": [E], "question": "Which product or offer should we show each customer next?",
     "questions": ["which product will the customer buy next", "next best offer",
                   "recommend the next product category for each customer", "which offer should we send each customer",
                   "predict the next purchase category", "next best action for each customer"],
     "task": "multiclass", "time": "time_split", "primary_metric": "f1_macro",
     "metric_why": "Many offers with uneven popularity; f1_macro stops rare offers from being ignored.",
     "unit": "customer at a snapshot date",
     "target_hint": [_x("next_product|next_category|next_offer|next_best_offer|next_purchase_category|offer|category"),
                     _w(r"next_(product|category|offer)\w*")],
     "leakage_patterns": [_w(r"redeem\w*|offer_accepted_(at|date)|next_order_(id|date|amount)")],
     "needed_columns": [_w(r"last_product\w*|last_category\w*|previous_\w+"), _w("recency|frequency|monetary|spend"),
                        _w("age|segment|tier"), _w("channel"), _w("products?_owned|holdings|num_products")],
     "families_prior": {"lightgbm": 1.2, "catboost": 1.1}},
    {"id": "sales_revenue_forecast", "name": "Sales and revenue forecast (store, region or company)",
     "domain": "sales_marketing", "segments": [S, M, E],
     "question": "How much revenue will each store, region or the business make next week, month or quarter?",
     "questions": ["forecast monthly revenue", "predict weekly sales per store", "revenue forecast for next quarter",
                   "how much will we sell next month", "forecast daily sales for each location",
                   "project sales by region for the budget", "predict turnover per branch", "sales forecasting"],
     "task": "regression", "time": "forecast", "primary_metric": "mae",
     "metric_why": "Planners compare forecasts to actuals in currency; MAE reads in currency and targets the "
                   "median. Use rmse when misses on peak days cost disproportionately.",
     "unit": "store (or region) per day, week or month",
     "target_hint": [_x("sales|revenue|weekly_sales|daily_sales|monthly_revenue|turnover|net_sales|gross_sales|amount"),
                     _w("sales|revenue|turnover")],
     "leakage_patterns": [_x("customers|customer_count|transactions|num_transactions|footfall"),
                          _w(r"(actual|realized)_\w+")],
     "needed_columns": [_w("date|week|month|period|ds"), _w(r"store\w*|branch|location|region"),
                        _w(r"promo\w*|discount\w*|campaign"), _w(r"holiday\w*|event\w*"), _w(r"price\w*")],
     "families_prior": {**FORECAST}},
    {"id": "session_conversion", "name": "Website session purchase intent", "domain": "sales_marketing",
     "segments": [S, E], "question": "Will this website visit end in a purchase?",
     "questions": ["will this visitor buy", "predict which website sessions convert", "online shopper purchase intention",
                   "predict checkout conversion from browsing behaviour", "which visitors are likely to purchase today",
                   "predict cart abandonment"],
     "task": "binary", "time": "time_split", "primary_metric": "roc_auc",
     "metric_why": "Offers go to the most likely buyers, so ranking (AUC); roughly 15 percent of sessions convert.",
     "unit": "session",
     "target_hint": [_x("revenue|purchased|converted|conversion|bought|ordered|abandoned"),
                     _w(r"purchas\w*|convert\w*|abandon\w*")],
     "leakage_patterns": [_w(r"order_(id|value|total)|transaction_(id|value)|checkout_completed|payment\w*|thank_you\w*")],
     "needed_columns": [_w(r"page_?views|pages|product_related\w*|administrative\w*|informational\w*"),
                        _w(r"duration\w*|time_on\w*"), _w(r"bounce\w*|exit\w*"), _w(r"traffic\w*|source|referrer|channel"),
                        _w("device|browser|visitor_type|returning")],
     "families_prior": {"lightgbm": 1.2, "xgboost": 1.1}},
    {"id": "trial_conversion", "name": "Free trial to paid conversion (product qualified leads)",
     "domain": "sales_marketing", "segments": [S, M],
     "question": "Which trial users or workspaces will become paying customers?",
     "questions": ["which trial users will convert to paid", "predict free to paid conversion",
                   "score product qualified leads", "find trials most likely to upgrade",
                   "which signups become paying customers", "predict freemium upgrade"],
     "task": "binary", "time": "time_split", "primary_metric": "roc_auc",
     "metric_why": "Sales assist reaches out to the top trials; ranking (AUC) matters and positives are few.",
     "unit": "trial account at day N of the trial",
     "target_hint": [_x("converted|is_converted|paid|is_paid|paying|is_paying|upgraded|conversion"),
                     _w(r"convert\w*|paid|paying")],
     "leakage_patterns": [_w(r"subscription_(start|id|date)|first_payment\w*|payment_(date|id)"),
                          _w(r"plan_price|mrr|arr|invoice\w*"), _w("converted_(at|date)|upgrade_(date|at)"),
                          _w("card_on_file|billing_(start|id)")],
     "needed_columns": [_w(r"signup\w*|source|channel|utm\w*"), _w("sessions?|events?|actions?|days_active"),
                        _w("invites?|teammates?|seats?"), _w("integrations?|workflows?|projects?"),
                        _w(r"activated|activation\w*|onboard\w*")],
     "families_prior": {"lightgbm": 1.2, "catboost": 1.1}},
    # ---- finance
    {"id": "invoice_late_payment", "name": "Invoice late payment", "domain": "finance", "segments": [S, M, E],
     "question": "Which open invoices will be paid late?",
     "questions": ["which invoices will be paid late", "predict late payment on invoices",
                   "which customers will pay after the due date", "prioritize collections by risk of late payment",
                   "flag invoices at risk of going overdue", "accounts receivable late payment risk"],
     "task": "binary", "time": "time_split", "primary_metric": "roc_auc",
     "metric_why": "Collectors call in order of risk, so AUC. For the number of days late, use a regression "
                   "target with mae.",
     "unit": "invoice at issue date",
     "target_hint": [_x("late|is_late|paid_late|overdue|is_overdue|late_payment|delayed"), _w(r"late\w*|overdue\w*")],
     "leakage_patterns": [_w(r"pay(ment)?_date|paid_(at|date|on)|clear\w*_date|days_to_pay|days_late|days_overdue"),
                          _w(r"amount_paid|paid_amount|outstanding_after\w*"),
                          _w(r"collection_status|dunning\w*|write_?off\w*")],
     "needed_columns": [_w("invoice_amount|amount|total"), _w("terms?|payment_terms|net_days"),
                        _w("due_date|issue_date|invoice_date"), _w(r"customer\w*|client\w*"),
                        _w(r"avg_days_late|history\w*|prior_late\w*"), _w("industry|country|currency")],
     "families_prior": {"lightgbm": 1.2, "catboost": 1.2}},
    {"id": "cash_flow_forecast", "name": "Cash flow forecast", "domain": "finance", "segments": [S, M, E],
     "question": "How much cash will come in and go out each week for the next quarter?",
     "questions": ["forecast our cash flow", "predict weekly cash balance", "how much cash will we have next month",
                   "forecast receivables collections by week", "cash position forecast for treasury",
                   "predict net cash flow per week", "forecast monthly expenses per cost center"],
     "task": "regression", "time": "forecast", "primary_metric": "mae",
     "metric_why": "Treasury reads errors in currency; MAE is interpretable and less driven by one lumpy payment.",
     "unit": "company or account per week",
     "target_hint": [_x("net_cash_flow|cash_flow|cashflow|cash_balance|balance|inflow|outflow|net_flow|expenses"),
                     _w(r"cash\w*|inflow\w*|outflow\w*")],
     "leakage_patterns": [_w(r"(actual|realized|reconciled)_\w+|closing_balance|ending_balance")],
     "needed_columns": [_w("date|week|month|period"), _w(r"receivables?|ar_\w+|invoices?_due"),
                        _w(r"payables?|ap_\w+|bills?_due"), _w("payroll|salaries"), _w("revenue|sales|bookings")],
     "families_prior": {**FORECAST}},
    {"id": "collections_recovery", "name": "Collections recovery", "domain": "finance", "segments": [S, E],
     "question": "Which delinquent accounts will pay if we contact them?",
     "questions": ["which overdue accounts will pay", "predict collection success", "prioritize debt collection calls",
                   "probability of recovering a past due balance", "which delinquent customers will cure",
                   "score accounts in collections"],
     "task": "binary", "time": "time_split", "primary_metric": "roc_auc",
     "metric_why": "Agents work accounts in score order; AUC measures that ranking.",
     "unit": "delinquent account at placement",
     "target_hint": [_x("paid|recovered|cured|collected|promise_kept|is_recovered"), _w(r"recover\w*|cured|collected")],
     "leakage_patterns": [_w(r"amount_(recovered|collected)|recovered_amount|payment_received\w*|settle\w*|"
                             r"write_?off\w*|closed_(at|date)")],
     "needed_columns": [_w(r"balance|amount_due|past_due\w*"), _w("days_past_due|dpd|days_delinquent"),
                        _w(r"contact\w*|attempts?|calls?"), _w(r"promise\w*|ptp"), _w(r"history\w*|prior_\w+")],
     "families_prior": {"lightgbm": 1.2, "logreg": 1.1}},
    # ---- risk and fraud
    {"id": "credit_default", "name": "Credit default risk", "domain": "risk_fraud", "segments": [S, E],
     "question": "Will this borrower default on the loan or card?",
     "questions": ["predict loan default", "which applicants will not repay", "credit risk score for loan applications",
                   "probability of default for each borrower", "who will miss payments on their loan",
                   "predict charge offs", "score credit applications"],
     "task": "binary", "time": "time_split", "primary_metric": "roc_auc",
     "metric_why": "Credit is judged on ranking (AUC, Gini = 2 AUC minus 1) before a cutoff is set; "
                   "defaults are often under 10 percent.",
     "unit": "loan application or account at origination",
     "target_hint": [_x("default|is_default|defaulted|bad|bad_loan|charged_off|delinquent|loan_default|"
                        "serious_dlqin2yrs|target"), _w(r"default\w*|charge\w*off|delinquen\w*")],
     "leakage_patterns": [_w("loan_status"), _w(r"recover\w*|collection\w*"),
                          _w(r"last_pymnt\w*|last_payment\w*|total_rec_\w+|total_pymnt\w*|out_prncp\w*|next_pymnt\w*"),
                          _w(r"charge_?off_date|settlement\w*|debt_settlement\w*|hardship\w*")],
     "needed_columns": [_w(r"income|annual_inc\w*|salary"), _w("loan_amnt|loan_amount|amount|credit_limit"),
                        _w(r"dti|debt\w*"), _w(r"credit_score|fico\w*|score"), _w("term|interest_rate|int_rate"),
                        _w(r"emp_length|employment\w*|job"), _w("purpose|home_ownership")],
     "families_prior": {"lightgbm": 1.2, "catboost": 1.1, "logreg": 1.3}},
    {"id": "transaction_fraud", "name": "Transaction fraud detection", "domain": "risk_fraud", "segments": [S, M, E],
     "question": "Is this payment, order or transaction fraudulent?",
     "questions": ["flag fraud", "flag fraudulent transactions", "detect fraud in card payments",
                   "which transactions are fraudulent", "predict chargebacks", "fraud detection model for payments",
                   "catch fraudulent orders before shipping"],
     "task": "binary", "time": "time_split", "primary_metric": "f1_macro",
     "metric_why": "Fraud is often under 1 percent; AUC can look great while the alert queue is mostly false "
                   "alarms. f1_macro scores the actual flag; check precision at the chosen threshold.",
     "unit": "transaction",
     "target_hint": [_x("is_fraud|isfraud|fraud|fraudulent|is_fraudulent|fraud_flag|fraud_label"),
                     _x("chargeback|is_chargeback"), _x("class|label"), _w(r"fraud\w*|chargeback\w*")],
     "leakage_patterns": [_w(r"chargeback_(date|amount|reason)|dispute\w*"),
                          _w(r"investigat\w*|reviewed_by|review_(outcome|decision)|case_id|analyst\w*"),
                          _w(r"fraud_(reported|type|reason)|reported_fraud"),
                          _w(r"blocked|account_blocked|card_blocked|refund\w*|reversal\w*")],
     "needed_columns": [_w("amount|amt|value"), _w(r"merchant\w*|mcc|category"), _w("time|timestamp|hour|step"),
                        _w(r"device\w*|ip\w*|browser"), _w(r"country|location|distance\w*|lat|long?"),
                        _w(r"velocity\w*|count_\w+|txn_count\w*"), _w(r"card\w*|account_age\w*|customer_age\w*")],
     "families_prior": {"lightgbm": 1.3, "xgboost": 1.2, "catboost": 1.1, "mlp": 0.8, "tabicl": 0.7}},
    {"id": "insurance_claim_fraud", "name": "Insurance claim fraud", "domain": "risk_fraud", "segments": [E],
     "question": "Is this insurance claim fraudulent and worth a special investigation?",
     "questions": ["detect fraudulent insurance claims", "which claims should go to the special investigations unit",
                   "predict claim fraud", "flag suspicious auto insurance claims", "score claims for fraud risk",
                   "which policies are fraudulent"],
     "task": "binary", "time": "time_split", "primary_metric": "f1_macro",
     "metric_why": "Investigators can open few cases and fraud is rare; f1_macro scores the referral flag.",
     "unit": "claim at first notice of loss",
     "target_hint": [_x("fraud_reported|is_fraud|fraud|fraudulent|fraud_flag"), _w(r"fraud\w*")],
     "leakage_patterns": [_w(r"siu_\w+|investigat\w*|referral_(outcome|result)"),
                          _w(r"claim_(status|denied|decision)|denied|paid_amount|payout\w*|settle\w*"),
                          _w("closed_(at|date)")],
     "needed_columns": [_w(r"claim_amount|total_claim\w*|injury_claim|property_claim|vehicle_claim"),
                        _w(r"policy_\w+|months_as_customer|tenure"), _w(r"incident_\w+"),
                        _w(r"witnesses|police_report\w*"), _w(r"insured_\w+|age"), _w(r"deductable|deductible|premium\w*")],
     "families_prior": {"lightgbm": 1.2, "catboost": 1.2, "xgboost": 1.1}},
    {"id": "aml_alert_scoring", "name": "Anti money laundering alert scoring", "domain": "risk_fraud",
     "segments": [E], "question": "Which AML alerts will turn into a suspicious activity report?",
     "questions": ["score anti money laundering alerts", "which aml alerts are true positives",
                   "predict suspicious activity reports", "reduce false positives in transaction monitoring",
                   "prioritize aml alerts for investigators", "detect money laundering"],
     "task": "binary", "time": "time_split", "primary_metric": "roc_auc",
     "metric_why": "Investigators work alerts in score order; AUC measures that ranking and supports a "
                   "documented cutoff.",
     "unit": "alert",
     "target_hint": [_x("sar|sar_filed|is_sar|suspicious|true_positive|productive"), _w(r"sar\w*|suspicious\w*")],
     "leakage_patterns": [_w(r"sar_(date|id|filed_date)|case_(closed|outcome|disposition)\w*|disposition\w*"),
                          _w(r"investigator\w*|analyst\w*|notes?|narrative\w*")],
     "needed_columns": [_w(r"amount\w*|total_\w+|sum_\w+"), _w(r"count\w*|num_\w+|txn\w*"),
                        _w(r"country\w*|jurisdiction|high_risk\w*"), _w("customer_type|segment|occupation|industry"),
                        _w(r"alert_type|rule\w*|scenario\w*")],
     "families_prior": {"lightgbm": 1.2, "xgboost": 1.1, "logreg": 1.1}},
    {"id": "application_fraud", "name": "Account opening and application fraud", "domain": "risk_fraud",
     "segments": [M, E], "question": "Is this new account, signup or credit application fake or fraudulent?",
     "questions": ["detect fake account signups", "predict application fraud", "flag fraudulent loan applications",
                   "identify synthetic identities at onboarding", "which new accounts are fraudsters",
                   "detect bank account opening fraud"],
     "task": "binary", "time": "time_split", "primary_metric": "f1_macro",
     "metric_why": "Fraud is rare and onboarding needs an accept or review decision; f1_macro scores that flag.",
     "unit": "application or signup",
     "target_hint": [_x("fraud_bool|is_fraud|fraud|fraudulent|fake|is_fake|synthetic"), _w(r"fraud\w*|fake\w*")],
     "leakage_patterns": [_w(r"account_(closed|blocked|banned)\w*|banned|suspended\w*"),
                          _w(r"first_payment_default|fpd|chargeback\w*"),
                          _w("review_(outcome|decision)|manual_review_result|kyc_(result|decision)")],
     "needed_columns": [_w(r"email\w*"), _w(r"phone\w*"), _w(r"device\w*|os|browser"), _w(r"ip\w*|country|zip\w*"),
                        _w(r"income|employment\w*|housing\w*"), _w(r"velocity\w*|count\w*|session\w*")],
     "families_prior": {"lightgbm": 1.3, "xgboost": 1.2, "catboost": 1.1}},
    {"id": "claim_probability", "name": "Insurance claim probability (risk per policy)", "domain": "risk_fraud",
     "segments": [E], "question": "Will this policyholder file a claim in the next year?",
     "questions": ["predict whether a driver files a claim next year", "probability of an insurance claim per policy",
                   "which policyholders will make a claim", "risk score for auto insurance customers",
                   "predict claim frequency for underwriting", "safe driver prediction"],
     "task": "binary", "time": "time_split", "primary_metric": "roc_auc",
     "metric_why": "Underwriting uses the normalized Gini (2 AUC minus 1), a ranking metric.",
     "unit": "policy year",
     "target_hint": [_x("claim|target|has_claim|claimed|claim_flag|is_claim"), _w(r"claim\w*")],
     "leakage_patterns": [_w(r"claim_(amount|cost|paid|date)|loss\w*|paid\w*|incurred\w*|reserve\w*")],
     "needed_columns": [_w("age|driver_age"), _w(r"vehicle\w*|car_\w+"), _w(r"region|zip\w*|territory"),
                        _w("prior_claims?|claims_history|bonus_malus"), _w(r"coverage\w*|deductible|premium")],
     "families_prior": {"lightgbm": 1.2, "xgboost": 1.1, "catboost": 1.1}},
    {"id": "claim_severity", "name": "Insurance claim severity (cost of a claim)", "domain": "risk_fraud",
     "segments": [E], "question": "How much will this claim end up costing?",
     "questions": ["predict the cost of each insurance claim", "estimate claim severity",
                   "how much will this claim pay out", "set initial reserves for new claims",
                   "predict loss amount per claim", "claims cost prediction"],
     "task": "regression", "time": "time_split", "primary_metric": "mae",
     "metric_why": "Claim costs are heavy tailed; MAE (the Allstate benchmark metric) keeps a few huge claims "
                   "from dominating.",
     "unit": "claim at first notice of loss",
     "target_hint": [_x("loss|claim_amount|claim_cost|severity|paid_amount|incurred|total_paid|ultimate_loss|cost"),
                     _w(r"loss\w*|severity|claim_(amount|cost)")],
     "leakage_patterns": [_w(r"settle\w*|final_reserve|reserve_final|closed_(at|date)|litigation_outcome|paid_to_date")],
     "needed_columns": [_w(r"claim_type|coverage\w*|line"), _w(r"injury\w*|damage\w*|body_part"),
                        _w(r"policy\w*|insured\w*"), _w(r"vehicle\w*|property\w*"), _w(r"region|state|zip\w*"),
                        _w("report_lag|days_to_report|incident_date")],
     "families_prior": {"lightgbm": 1.2, "catboost": 1.2, "xgboost": 1.1}},
    # ---- operations and supply chain
    {"id": "demand_forecast", "name": "Demand forecast (units per product and location)", "domain": "operations",
     "segments": [S, M, E],
     "question": "How many units of each product will each store or warehouse sell next week?",
     "questions": ["forecast weekly demand per store", "predict units sold per product next week",
                   "demand forecasting for inventory planning", "how many items will we sell per sku",
                   "forecast daily demand by store and item", "predict product demand for replenishment",
                   "forecast order quantities per warehouse"],
     "task": "regression", "time": "forecast", "primary_metric": "mae",
     "metric_why": "Demand is intermittent with many zeros; MAE targets the median and reads in units. Use "
                   "rmse when stockouts on peaks are the costly error.",
     "unit": "product and location per week (or day)",
     "target_hint": [_x("units|units_sold|quantity|qty|demand|sales_qty|unit_sales|sold|order_qty|volume"),
                     _x("sales|item_cnt_day|item_cnt|orders"), _w(r"units\w*|qty|quantity|demand")],
     "leakage_patterns": [_w(r"lost_sales|stockout\w*|stock_out\w*"),
                          _w(r"(end|closing)_(stock|inventory)\w*|fill_rate|fulfilled\w*"), _w("returns?_qty|returned_units")],
     "needed_columns": [_w("date|week|day|period|ds|wm_yr_wk"), _w(r"store\w*|location|warehouse|shop\w*|dc"),
                        _w(r"item\w*|sku|product\w*|article"), _w(r"price\w*|sell_price"),
                        _w(r"promo\w*|discount\w*|on_promotion|onpromotion"), _w(r"holiday\w*|event\w*|snap\w*")],
     "families_prior": {**FORECAST}},
    {"id": "stockout_risk", "name": "Stockout and backorder risk", "domain": "operations", "segments": [S, E],
     "question": "Which products will run out of stock before the next delivery?",
     "questions": ["which products will go out of stock", "predict stockouts next week",
                   "flag items at risk of running out", "backorder prediction", "predict out of stock risk per store",
                   "which skus will be backordered"],
     "task": "binary", "time": "time_split", "primary_metric": "f1_macro",
     "metric_why": "Stockouts are rare and planners act on a flag; f1_macro weighs misses against false alarms.",
     "unit": "product and location per week",
     "target_hint": [_x("stockout|is_stockout|out_of_stock|oos|went_on_backorder|backorder|backordered"),
                     _w(r"stock_?out\w*|backorder\w*|oos")],
     "leakage_patterns": [_w(r"lost_sales|backorder_qty|unfilled\w*|end_(stock|inventory)|closing_(stock|inventory)")],
     "needed_columns": [_w(r"on_hand|inventory|national_inv|stock_level\w*"), _w("lead_time"),
                        _w(r"forecast\w*|sales\w*"), _w(r"in_transit\w*|on_order\w*"),
                        _w(r"reorder\w*|min_bank|safety_stock")],
     "families_prior": {"lightgbm": 1.2, "xgboost": 1.2}},
    {"id": "late_delivery", "name": "Late delivery risk", "domain": "operations", "segments": [S, M, E],
     "question": "Which orders or shipments will arrive late?",
     "questions": ["which orders will be delivered late", "predict late deliveries", "flag shipments at risk of delay",
                   "on time delivery prediction", "will this shipment miss its promised date",
                   "predict delivery delays by carrier"],
     "task": "binary", "time": "time_split", "primary_metric": "roc_auc",
     "metric_why": "Ops teams rank shipments to intervene; AUC. Late rates are often high, so ranking is the need.",
     "unit": "order or shipment at dispatch",
     "target_hint": [_x("late|is_late|late_delivery|late_delivery_risk|delayed|is_delayed|on_time|ontime"),
                     _w(r"late\w*|delay\w*")],
     "leakage_patterns": [_w(r"actual_\w+|delivered_(at|date)|delivery_date|arrival_(date|time)|"
                             r"days_for_shipping_real|delivery_status|delay_days|days_late")],
     "needed_columns": [_w("shipping_mode|ship_mode|service_level|mode"),
                        _w(r"scheduled\w*|promised\w*|planned\w*"), _w(r"carrier\w*"),
                        _w(r"origin\w*|destination\w*|region|country|city"), _w(r"weight\w*|volume|quantity|qty"),
                        _w(r"order_date|dispatch\w*|ship_date")],
     "families_prior": {"lightgbm": 1.2, "catboost": 1.1}},
    {"id": "delivery_eta", "name": "Delivery time (ETA)", "domain": "operations", "segments": [S, E],
     "question": "How long will this delivery or trip take?",
     "questions": ["predict delivery time", "estimate eta for each order", "how long will the trip take",
                   "predict transit time in days", "estimate food delivery duration",
                   "predict shipping time from warehouse to customer"],
     "task": "regression", "time": "time_split", "primary_metric": "mae",
     "metric_why": "Customers feel absolute minutes late; MAE reads in minutes and ignores rare stuck orders.",
     "unit": "order or trip",
     "target_hint": [_x("delivery_time|eta|transit_days|transit_time|duration|trip_duration|delivery_minutes|time_taken"),
                     _w(r"duration|eta|transit\w*|delivery_(time|minutes|days)")],
     "leakage_patterns": [_w(r"delivered_(at|time|date)|arrival\w*|dropoff\w*|actual_\w+|end_time|completed_at")],
     "needed_columns": [_w(r"distance\w*|km|miles"), _w(r"pickup\w*|start\w*|created\w*"),
                        _w(r"carrier|courier|driver\w*|vehicle\w*"), _w(r"weather\w*|traffic\w*"),
                        _w("region|zone|city|origin|destination")],
     "families_prior": {"lightgbm": 1.3, "xgboost": 1.1}},
    {"id": "supplier_lead_time", "name": "Supplier lead time", "domain": "operations", "segments": [M, E],
     "question": "How many days will this purchase order take to arrive from the supplier?",
     "questions": ["predict supplier lead times", "how long until this purchase order arrives",
                   "which suppliers will deliver late", "estimate procurement lead time per order",
                   "predict days from order to receipt", "supplier delivery reliability forecast"],
     "task": "regression", "time": "time_split", "primary_metric": "mae",
     "metric_why": "Planners set safety stock in days; MAE in days is readable and robust to a few very late POs.",
     "unit": "purchase order line",
     "target_hint": [_x("lead_time|lead_time_days|days_to_receive|actual_lead_time|delivery_days"), _w(r"lead_time\w*")],
     "leakage_patterns": [_w(r"receipt_date|received_(at|date|qty)|goods_receipt\w*|gr_date|invoice_date")],
     "needed_columns": [_w(r"supplier\w*|vendor\w*"), _w(r"item\w*|material\w*|category"), _w("order_qty|quantity|qty"),
                        _w(r"order_date|po_date|created\w*"), _w(r"promised\w*|quoted_lead\w*|planned\w*"),
                        _w(r"country|origin|incoterm\w*|transport\w*")],
     "families_prior": {"catboost": 1.2, "lightgbm": 1.2}},
    {"id": "call_volume_forecast", "name": "Contact center and staffing volume forecast", "domain": "operations",
     "segments": [M, E], "question": "How many calls, chats or tickets will arrive per interval, so we can staff?",
     "questions": ["forecast call volume per hour", "how many support tickets will we get next week",
                   "predict contact center volume for staffing", "forecast daily chats and calls",
                   "workforce planning forecast for agents", "predict the number of orders per hour for staffing"],
     "task": "regression", "time": "forecast", "primary_metric": "mae",
     "metric_why": "Staffing reads the error as people per interval; MAE is readable and robust to outage spikes.",
     "unit": "queue per hour or day",
     "target_hint": [_x("calls|call_volume|volume|contacts|tickets|tickets_created|chats|arrivals|count"),
                     _w("volume|calls|contacts|arrivals")],
     "leakage_patterns": [_w(r"handled\w*|answered\w*|abandon\w*|service_level|asa|aht")],
     "needed_columns": [_w("date|datetime|timestamp|interval|hour|ds"), _w("day_of_week|dow|weekday"),
                        _w(r"holiday\w*|event\w*"), _w(r"campaign\w*|marketing\w*|outage\w*"), _w("queue|channel|skill")],
     "families_prior": {**FORECAST}},
    {"id": "energy_load_forecast", "name": "Energy load forecast", "domain": "operations", "segments": [E],
     "question": "How much electricity or gas will each site use per hour tomorrow?",
     "questions": ["forecast electricity demand per hour", "predict energy consumption for each building",
                   "load forecasting for tomorrow", "how much power will we use next week",
                   "forecast gas usage per site", "predict kwh consumption per meter"],
     "task": "regression", "time": "forecast", "primary_metric": "rmse",
     "metric_why": "Grid and capacity costs are driven by peaks; RMSE penalizes big misses at peak hours.",
     "unit": "site or meter per hour",
     "target_hint": [_x("load|consumption|kwh|energy|demand|mw|power|usage|meter_reading"),
                     _w(r"load|kwh|consumption|energy\w*")],
     "leakage_patterns": [_w(r"(actual|metered)_\w+|bill\w*_amount")],
     "needed_columns": [_w("datetime|timestamp|date|hour|ds"), _w(r"temp\w*|weather\w*|humidity|wind\w*|solar\w*"),
                        _w(r"holiday\w*"), _w(r"building\w*|site\w*|meter\w*|region"),
                        _w("square_feet|sqft|floor_area|occupancy")],
     "families_prior": {**FORECAST}},
    {"id": "returns_prediction", "name": "Product return prediction", "domain": "operations", "segments": [S, E],
     "question": "Will this order or item be returned?",
     "questions": ["which orders will be returned", "predict product returns", "flag purchases likely to be sent back",
                   "return probability per order line", "predict returns for fashion orders",
                   "which customers return items often"],
     "task": "binary", "time": "time_split", "primary_metric": "roc_auc",
     "metric_why": "Interventions (size advice, review) go to the riskiest orders; AUC measures that ranking.",
     "unit": "order line",
     "target_hint": [_x("returned|is_returned|return|return_flag|was_returned"), _w(r"return\w*")],
     "leakage_patterns": [_w(r"return_(date|reason|id|status)|refund\w*|restock\w*|rma\w*|credit_note\w*")],
     "needed_columns": [_w(r"category|product\w*|sku"), _w(r"price|discount\w*"), _w(r"size\w*|color|fit"),
                        _w(r"customer_return\w*|return_rate|prior_returns"), _w(r"channel|payment\w*|shipping\w*")],
     "families_prior": {"catboost": 1.2, "lightgbm": 1.2}},
    {"id": "booking_cancellation", "name": "Booking or reservation cancellation", "domain": "operations",
     "segments": [S, E], "question": "Will this hotel, restaurant or service booking be cancelled?",
     "questions": ["which bookings will be cancelled", "predict hotel reservation cancellations", "will the guest cancel",
                   "forecast cancellation risk for reservations", "flag bookings likely to cancel for overbooking",
                   "predict order cancellations before shipping"],
     "task": "binary", "time": "time_split", "primary_metric": "roc_auc",
     "metric_why": "Overbooking and reminders act on the riskiest bookings; AUC. Cancel rates are often 25 "
                   "percent or more.",
     "unit": "booking at reservation time",
     "target_hint": [_x("is_canceled|is_cancelled|canceled|cancelled|cancellation|booking_status|cancel"),
                     _w(r"cancel\w*")],
     "leakage_patterns": [_w(r"reservation_status\w*|cancel\w*_(date|at|reason)|refund\w*|assigned_room\w*|"
                             r"check_?in_(time|at)|checked_in")],
     "needed_columns": [_w("lead_time"), _w(r"deposit\w*"), _w("adr|rate|price"),
                        _w("market_segment|channel|distribution_channel"),
                        _w(r"previous_cancellations|prior_cancel\w*"), _w(r"arrival\w*|stay\w*|nights?"),
                        _w("special_requests|total_of_special_requests|adults|children")],
     "families_prior": {"lightgbm": 1.2, "catboost": 1.2, "xgboost": 1.1}},
    # ---- HR
    {"id": "employee_attrition", "name": "Employee attrition", "domain": "hr", "segments": [S, M, E],
     "question": "Which employees are likely to leave in the next year?",
     "questions": ["which employees will quit", "predict employee attrition", "who is at risk of leaving the company",
                   "staff turnover prediction", "flight risk score for employees",
                   "predict resignations in the next 12 months"],
     "task": "binary", "time": "time_split", "primary_metric": "roc_auc",
     "metric_why": "HR ranks people for stay interviews; AUC. Leavers are a minority and HR needs to explain "
                   "the model, so linear models get a boost.",
     "unit": "employee at a snapshot date",
     "target_hint": [_x("attrition|left|quit|resigned|terminated|turnover|exited|leaver|is_leaver"),
                     _w(r"attrition|resign\w*|turnover")],
     "leakage_patterns": [_w(r"termination\w*|term_date|separation\w*|exit_\w+|last_(day|working_day)|"
                             r"date_of_termination|dateoftermination"),
                          _w(r"rehire\w*|severance\w*|final_pay\w*|notice_(date|period_start)|employment_status|emp_status")],
     "needed_columns": [_w(r"tenure|years_at_company|years_\w+"), _w(r"salary|monthly_income|pay\w*|compensation"),
                        _w("job_level|level|grade|role|job_role"), _w("department|team"), _w(r"overtime|hours\w*"),
                        _w(r"satisfaction\w*|engagement\w*|performance\w*"), _w(r"promotion\w*")],
     "families_prior": {"logreg": 1.3, "catboost": 1.1, "lightgbm": 1.1}},
    {"id": "offer_acceptance", "name": "Candidate offer acceptance and hiring success", "domain": "hr",
     "segments": [M, E], "question": "Will this candidate accept our offer, or get through the hiring process?",
     "questions": ["will the candidate accept the job offer", "predict offer acceptance",
                   "which applicants will be hired", "predict which candidates drop out of the hiring funnel",
                   "candidate success prediction", "which recruits will join after the offer"],
     "task": "binary", "time": "time_split", "primary_metric": "roc_auc",
     "metric_why": "Recruiters prioritise candidates by likelihood; AUC measures that ranking.",
     "unit": "candidate or offer",
     "target_hint": [_x("accepted|offer_accepted|hired|joined|is_hired"), _w(r"accept\w*|hired|joined")],
     "leakage_patterns": [_w(r"start_date|join(ing)?_date|onboard\w*|employee_(id|number)|hire_date|decline_reason")],
     "needed_columns": [_w("source|channel|referral"), _w(r"offered_\w+|offer_\w+|salary\w*|ctc\w*"),
                        _w(r"expected_\w+|current_\w+"), _w(r"notice_period|notice\w*"),
                        _w("role|position|level|department"), _w(r"location|relocation\w*")],
     "families_prior": {"catboost": 1.2, "logreg": 1.2}},
    {"id": "performance_rating", "name": "Employee performance rating", "domain": "hr", "segments": [M, E],
     "question": "What performance rating will each employee get this cycle?",
     "questions": ["predict employee performance ratings", "which employees will be high performers",
                   "predict review scores for staff", "forecast performance category per employee",
                   "identify future top performers", "classify employees into performance bands"],
     "task": "multiclass", "time": "time_split", "primary_metric": "f1_macro",
     "metric_why": "Top and bottom bands are small; f1_macro keeps them from being ignored.",
     "unit": "employee per review cycle",
     "target_hint": [_x("performance_rating|rating|performance_score|perf_rating|performance|performance_band"),
                     _w(r"rating|perf\w*")],
     "leakage_patterns": [_w(r"bonus\w*|raise\w*|merit\w*|salary_increase\w*|calibrated_\w+|final_rating")],
     "needed_columns": [_w(r"tenure|length_of_service|years_\w+"), _w(r"training\w*|courses?"),
                        _w(r"previous_\w*rating|prior_rating|last_rating"), _w("department|role|level"),
                        _w("kpis?|goals?|awards?|projects?"), _w(r"manager\w*")],
     "families_prior": {"catboost": 1.2, "lightgbm": 1.1, "logreg": 1.1}},
    {"id": "salary_benchmark", "name": "Salary benchmarking", "domain": "hr", "segments": [S, M, E],
     "question": "What is a fair salary for this role, level and location?",
     "questions": ["predict salary for a job", "what should we pay for this role",
                   "estimate market compensation by title and location", "salary benchmarking model",
                   "predict pay for employees to find underpaid staff", "estimate base salary from experience"],
     "task": "regression", "time": "none", "primary_metric": "mae",
     "metric_why": "People reason about pay gaps in currency; MAE is readable and robust to executive outliers.",
     "unit": "employee or job posting",
     "target_hint": [_x("salary|base_salary|salary_in_usd|salary_usd|compensation|pay|annual_salary"),
                     _w(r"salary\w*|compensation|pay")],
     "leakage_patterns": [_w(r"bonus\w*|total_comp\w*|tax\w*|net_pay|salary_currency_amount")],
     "needed_columns": [_w("job_title|title|role|position"), _w("level|seniority|experience_level|grade"),
                        _w(r"years_\w+|experience\w*"), _w("location|country|city|company_location|employee_residence"),
                        _w("company_size|industry"), _w(r"education\w*|degree")],
     "families_prior": {"catboost": 1.3, "lightgbm": 1.1}},
    # ---- pricing
    {"id": "price_forecast", "name": "Price forecast per product (next period)", "domain": "pricing",
     "segments": [S, M, E], "question": "What will the price of each product (or input) be next month?",
     "questions": ["predict next month's price per product", "forecast future prices for each item",
                   "what will the price be next month", "forecast commodity and supplier prices",
                   "predict the market price of our products next quarter", "price forecast per product over time"],
     "task": "regression", "time": "forecast", "primary_metric": "rmse",
     "metric_why": "Prices move in levels and a few large misses break margins; RMSE punishes them and "
                   "targets the mean. Use mae if outlier months should not dominate.",
     "unit": "product per month (or week)",
     "target_hint": [_x(r"price|unit_price|avg_price|average_price|sell_price|selling_price|price_next\w*|next_price"),
                     _x("cost|unit_cost|close"), _w(r"price\w*")],
     "leakage_patterns": [_w(r"actual_\w+|realized_\w+|settle\w*_price")],
     "needed_columns": [_w("date|month|week|period|ds"), _w(r"product\w*|item\w*|sku|commodity"),
                        _w(r"cost\w*|input_price\w*|raw_material\w*"), _w(r"competitor\w*|market\w*|index"),
                        _w("demand|units|volume|sales"), _w(r"promo\w*|discount\w*")],
     "families_prior": {"lightgbm": 1.3, "xgboost": 1.1, "catboost": 1.1, "ridge": 1.1,
                        "random_forest": 0.7, "tabicl": 0.6}},
    {"id": "price_response", "name": "Price response and elasticity (units at a given price)",
     "domain": "pricing", "segments": [S, E],
     "question": "How many units will we sell at a given price, so we can pick the best price?",
     "questions": ["what happens to sales if we raise prices", "estimate price elasticity per product",
                   "find the optimal price for each product", "how does demand change with price",
                   "dynamic pricing model", "predict units sold at different price points",
                   "markdown optimization for clearance"],
     "task": "regression", "time": "time_split", "primary_metric": "mae",
     "metric_why": "The model predicts units at a price; MAE in units is readable. Elasticity read off it is "
                   "an association unless prices varied independently of demand.",
     "unit": "product per day or week at a price",
     "target_hint": [_x("units|units_sold|quantity|qty|demand|sales|sold|volume"), _w(r"units\w*|qty|quantity|demand")],
     "leakage_patterns": [_w("revenue|sales_amount|turnover|gross_sales")],
     "needed_columns": [_w(r"price\w*"), _w(r"discount\w*|markdown\w*|promo\w*"), _w(r"competitor\w*"),
                        _w("date|week|day"), _w(r"product\w*|item\w*|sku|category")],
     "families_prior": {"lightgbm": 1.2, "xgboost": 1.1, "ridge": 1.1}},
    {"id": "quote_win", "name": "B2B quote win probability at a price", "domain": "pricing", "segments": [M, E],
     "question": "Will this quote be accepted at the price we are offering?",
     "questions": ["will the customer accept this quote", "predict quote win rate at a given discount",
                   "probability a price quote converts to an order", "how much discount do we need to win the deal",
                   "predict whether a bid wins", "quote acceptance model for pricing"],
     "task": "binary", "time": "time_split", "primary_metric": "roc_auc",
     "metric_why": "Win curves by price need well ranked probabilities; AUC, then read calibration.",
     "unit": "quote",
     "target_hint": [_x("won|accepted|is_won|quote_won|converted|awarded|win"), _w(r"won|accept\w*|award\w*")],
     "leakage_patterns": [_w(r"order_(id|date|number)|po_number|po_\w+|invoice\w*"),
                          _w(r"final_(price|discount|amount)|booked\w*|closed_(at|date)")],
     "needed_columns": [_w("quoted_price|price|unit_price|net_price"), _w(r"discount\w*|list_price"),
                        _w(r"customer\w*|segment|industry"), _w(r"product\w*|sku|category"),
                        _w("quantity|qty|deal_size|amount"), _w(r"competitor\w*|region")],
     "families_prior": {"catboost": 1.2, "lightgbm": 1.1, "logreg": 1.1}},
    {"id": "resale_price", "name": "Used vehicle or equipment resale price", "domain": "pricing", "segments": [S, E],
     "question": "What is this used car, machine or item worth on the resale market?",
     "questions": ["predict used car prices", "estimate resale value of equipment", "how much is this vehicle worth",
                   "price used items for our listings", "predict the selling price of second hand products",
                   "trade in value estimate"],
     "task": "regression", "time": "none", "primary_metric": "mae",
     "metric_why": "Buyers and sellers think in currency per item; MAE is readable and robust to rare luxury listings.",
     "unit": "listing or item",
     "target_hint": [_x("price|sale_price|selling_price|sold_price|resale_value|value|price_usd"), _w(r"price\w*|value")],
     "leakage_patterns": [_w(r"price_per_\w+|final_price|hammer_price|days_to_sell|sold_(at|date)")],
     "needed_columns": [_w("make|brand|manufacturer"), _w(r"model\w*"), _w(r"year|age\w*|model_year"),
                        _w(r"mileage|odometer|km\w*|hours_used|usage"), _w(r"condition\w*|grade"),
                        _w("location|region|state")],
     "families_prior": {"catboost": 1.3, "lightgbm": 1.1}},
    {"id": "insurance_premium", "name": "Insurance premium (expected loss per policy)", "domain": "pricing",
     "segments": [E], "question": "What premium should we charge this policy for its expected losses?",
     "questions": ["set insurance premiums from risk", "predict expected loss per policy",
                   "estimate the premium for each customer", "insurance pricing model",
                   "predict annual insurance cost per policyholder", "price health insurance by customer profile"],
     "task": "regression", "time": "time_split", "primary_metric": "rmse",
     "metric_why": "Pricing needs the expected (mean) loss; RMSE targets the mean, while MAE would predict near "
                   "zero for the many policies without claims.",
     "unit": "policy year",
     "target_hint": [_x("premium|pure_premium|expected_loss|charges|loss_cost|annual_premium"),
                     _w(r"premium\w*|charges|loss_cost")],
     "leakage_patterns": [_w(r"claim_(amount|paid|count)\w*|paid_losses|incurred\w*|loss_ratio")],
     "needed_columns": [_w("age"), _w(r"bmi|smoker|health\w*"), _w(r"vehicle\w*|driver\w*"),
                        _w(r"region|zip\w*|territory"), _w(r"coverage\w*|deductible\w*"), _w(r"exposure|policy_\w+")],
     "families_prior": {"lightgbm": 1.2, "xgboost": 1.1}},
    # ---- real estate
    {"id": "house_price", "name": "Property value (automated valuation)", "domain": "real_estate",
     "segments": [S, E], "question": "What is this house or property worth?",
     "questions": ["predict house prices", "estimate the sale price of each house", "what is this property worth",
                   "automated valuation model for homes", "price homes for listing",
                   "estimate market value of real estate", "predict home sale price from features"],
     "task": "regression", "time": "none", "primary_metric": "mae",
     "metric_why": "Home values are right skewed; MAE reads in currency and is not ruled by a few mansions. "
                   "Split by sale date when the data spans years.",
     "unit": "property sale",
     "target_hint": [_x("sale_price|saleprice|price|sold_price|close_price|value|market_value|median_house_value"),
                     _w(r"price\w*|value")],
     "leakage_patterns": [_w(r"price_per_(sq\w*|m2|foot|meter)|ppsf|price_sqft|price_psf"),
                          _w("days_on_market|dom|cumulative_dom")],
     "needed_columns": [_w(r"sqft|square_feet|living_area|gr_liv_area|area|size|sqm"), _w("bedrooms?|beds|rooms"),
                        _w("bathrooms?|baths"), _w(r"age\w*|year_built|yr_built"),
                        _w(r"neighbou?rhood|zip\w*|postcode|location|lat\w*|lon\w*"),
                        _w(r"lot\w*|garage\w*|condition\w*|quality\w*")],
     "families_prior": {"lightgbm": 1.2, "catboost": 1.2, "xgboost": 1.1}},
    {"id": "rent_price", "name": "Rent estimate", "domain": "real_estate", "segments": [S, E],
     "question": "What monthly rent (or nightly rate) should this unit ask?",
     "questions": ["predict rent for an apartment", "what rent should we charge for this unit",
                   "estimate monthly rent from listing features", "rental price prediction",
                   "price short term rentals per night", "predict airbnb nightly price"],
     "task": "regression", "time": "none", "primary_metric": "mae",
     "metric_why": "Landlords reason in currency per month; MAE is readable and robust to luxury listings.",
     "unit": "unit or listing",
     "target_hint": [_x("rent|monthly_rent|rent_amount|rent_price|price|nightly_price"), _w(r"rent\w*|price")],
     "leakage_patterns": [_w(r"rent_per_\w+|price_per_\w+|revenue\w*|booked_nights|occupancy_rate\w*")],
     "needed_columns": [_w("sqft|square_feet|area|size|sqm"), _w("bedrooms?|beds|rooms"), _w("bathrooms?|baths"),
                        _w(r"neighbou?rhood|zip\w*|location|lat\w*|lon\w*|city"),
                        _w(r"amenit\w*|furnished|parking|pets?"), _w("room_type|property_type")],
     "families_prior": {"lightgbm": 1.2, "catboost": 1.2}},
    {"id": "occupancy_forecast", "name": "Occupancy forecast (hotel or property)", "domain": "real_estate",
     "segments": [S, E], "question": "What share of rooms or units will be occupied each night next month?",
     "questions": ["forecast hotel occupancy", "predict rooms sold per night", "forecast occupancy rate for next month",
                   "how full will the property be next week", "forecast vacancy for our buildings",
                   "predict nightly bookings per property"],
     "task": "regression", "time": "forecast", "primary_metric": "mae",
     "metric_why": "Revenue managers read the error in rooms or points of occupancy; MAE is readable.",
     "unit": "property per night or month",
     "target_hint": [_x("occupancy|occupancy_rate|occ|rooms_sold|occupied|occupied_units|vacancy|vacancy_rate|bookings"),
                     _w(r"occupan\w*|vacan\w*|rooms_sold")],
     "leakage_patterns": [_w(r"revenue\w*|revpar|adr_actual|actual_\w+|no_shows")],
     "needed_columns": [_w("date|night|stay_date|month|ds"), _w(r"on_the_books|otb|bookings_to_date|pickup\w*|reservations?"),
                        _w(r"event\w*|holiday\w*"), _w("price|rate|adr"), _w(r"property\w*|hotel\w*|building\w*")],
     "families_prior": {**FORECAST}},
    {"id": "lease_renewal", "name": "Tenant lease renewal", "domain": "real_estate", "segments": [S, E],
     "question": "Will this tenant renew the lease or move out?",
     "questions": ["will the tenant renew their lease", "predict tenant move outs", "which residents will not renew",
                   "lease renewal probability", "predict tenant turnover for our buildings",
                   "which commercial tenants will leave at lease end"],
     "task": "binary", "time": "time_split", "primary_metric": "roc_auc",
     "metric_why": "Property managers rank leases for retention offers; AUC.",
     "unit": "lease at N days before expiry",
     "target_hint": [_x("renewed|renewal|will_renew|moved_out|move_out|is_renewed"), _w(r"renew\w*|move_?out\w*")],
     "leakage_patterns": [_w(r"move_out_date|notice_(date|given)|new_lease\w*|renewal_(rent|date|signed)\w*|vacated\w*")],
     "needed_columns": [_w(r"rent\w*|rent_increase\w*"), _w("tenure|months_in_unit|lease_term"),
                        _w(r"maintenance\w*|work_orders?|complaints?"), _w(r"late_payments?|payment\w*|balance"),
                        _w(r"unit\w*|property\w*|building\w*")],
     "families_prior": {"lightgbm": 1.2, "logreg": 1.1}},
    # ---- healthcare administration
    {"id": "appointment_no_show", "name": "Appointment no show", "domain": "healthcare_admin", "segments": [S, E],
     "question": "Which booked appointments will the patient or client miss?",
     "questions": ["which patients will miss their appointment", "predict appointment no shows",
                   "flag appointments at risk of no show for reminders", "who will not show up to their booking",
                   "no show prediction for the clinic", "predict missed visits to overbook slots"],
     "task": "binary", "time": "time_split", "primary_metric": "roc_auc",
     "metric_why": "Reminder calls and overbooking go to the riskiest slots; AUC. No show rates run 10 to 30 percent.",
     "unit": "appointment at booking time",
     "target_hint": [_x("no_show|noshow|no_show_flag|missed|showed_up|attended|show"), _w(r"no_?show\w*|missed|attend\w*")],
     "leakage_patterns": [_w(r"check_?in\w*|arrival_(time|at)|arrived\w*|visit_duration|seen_by|billed\w*|"
                             r"charge\w*|cancel\w*_reason|rescheduled_to\w*|encounter_id")],
     "needed_columns": [_w(r"lead_time\w*|days_between|waiting_days|scheduled\w*"),
                        _w(r"prior_no_shows?|previous_no_shows?|no_show_history|past_missed\w*"), _w("age|gender"),
                        _w(r"insurance\w*|payer|scholarship"), _w(r"sms\w*|reminder\w*"),
                        _w("weekday|day_of_week|appointment_day|hour"), _w(r"distance\w*|neighbou?rhood|zip\w*")],
     "families_prior": {"lightgbm": 1.2, "catboost": 1.1, "logreg": 1.1}},
    {"id": "readmission", "name": "Hospital readmission within 30 days", "domain": "healthcare_admin",
     "segments": [E], "question": "Will this patient be readmitted within 30 days of discharge?",
     "questions": ["predict 30 day readmission", "which patients will be readmitted", "readmission risk at discharge",
                   "flag patients likely to come back to hospital", "predict unplanned readmissions",
                   "hospital readmission model for care management"],
     "task": "binary", "time": "time_split", "primary_metric": "roc_auc",
     "metric_why": "Care managers call the riskiest discharges; AUC is the standard metric in readmission studies.",
     "unit": "discharge (encounter)",
     "target_hint": [_x("readmitted|readmit|readmission|readmit_30|readmitted_30|is_readmitted|readmission_30d"),
                     _w(r"readmi\w*")],
     "leakage_patterns": [_w(r"readmi\w*_(date|id|days)|days_to_readmi\w*|next_admission\w*|post_discharge\w*|"
                             r"followup_(visit|outcome)\w*")],
     "needed_columns": [_w("age|gender"), _w(r"diag\w*|icd\w*"), _w("length_of_stay|los|time_in_hospital"),
                        _w(r"num_\w+|number_\w+|prior_admissions?"), _w("medications?|meds|insulin"),
                        _w(r"discharge_disposition\w*|admission_type\w*|admission_source\w*"),
                        _w(r"lab\w*|a1c\w*|glucose\w*")],
     "families_prior": {"lightgbm": 1.2, "catboost": 1.1, "logreg": 1.2}},
    {"id": "length_of_stay", "name": "Length of stay", "domain": "healthcare_admin", "segments": [E],
     "question": "How many days will this patient stay in the hospital?",
     "questions": ["predict length of stay", "how many days will the patient stay",
                   "estimate hospital stay duration at admission", "forecast bed days per admission",
                   "predict los for inpatients", "which admissions will have a long stay"],
     "task": "regression", "time": "time_split", "primary_metric": "mae",
     "metric_why": "Stays are right skewed; MAE in days is what bed managers plan with.",
     "unit": "admission",
     "target_hint": [_x("los|length_of_stay|lengthofstay|los_days|stay_days|time_in_hospital|stay"),
                     _w(r"los|length_of_stay|stay\w*")],
     "leakage_patterns": [_w(r"discharge_(date|time|disposition|status)\w*|discharged\w*|total_charges|"
                             r"total_costs|billed\w*")],
     "needed_columns": [_w(r"admission_type\w*|admit_type\w*|type_of_admission"), _w(r"diag\w*|drg\w*|icd\w*|severity\w*"),
                        _w(r"age\w*|gender"), _w(r"comorbid\w*|conditions?|risk_score"),
                        _w(r"admission_source\w*|department|ward|facility\w*"), _w("weekday|admit_day|admission_date")],
     "families_prior": {"lightgbm": 1.2, "catboost": 1.2}},
    {"id": "claim_denial", "name": "Medical claim denial", "domain": "healthcare_admin", "segments": [M, E],
     "question": "Will the payer deny this claim, so we can fix it before submission?",
     "questions": ["predict which claims will be denied", "claim denial prediction before submission",
                   "flag medical claims likely to be rejected by the payer", "which insurance claims will bounce",
                   "reduce denials in revenue cycle", "predict payer rejections"],
     "task": "binary", "time": "time_split", "primary_metric": "roc_auc",
     "metric_why": "Billers review the riskiest claims first; AUC measures that ranking.",
     "unit": "claim (or claim line) before submission",
     "target_hint": [_x("denied|is_denied|denial|rejected|is_rejected|claim_status|denial_flag"), _w(r"deni\w*|reject\w*")],
     "leakage_patterns": [_w(r"denial_(code|reason|date)|carc\w*|rarc\w*|remit\w*|adjustment_(reason|code)|"
                             r"paid_amount|payment_(date|amount)|allowed_amount|appeal\w*")],
     "needed_columns": [_w(r"payer\w*|insurer\w*|plan\w*"), _w(r"cpt\w*|hcpcs\w*|procedure\w*"), _w(r"icd\w*|diag\w*"),
                        _w(r"specialty|provider\w*|npi"), _w(r"place_of_service|pos|facility\w*"),
                        _w(r"prior_auth\w*|authorization\w*"), _w(r"billed_amount|charge\w*|units")],
     "families_prior": {"catboost": 1.3, "lightgbm": 1.1}},
    {"id": "patient_volume_forecast", "name": "Patient volume forecast", "domain": "healthcare_admin",
     "segments": [S, E], "question": "How many patients will arrive per day or hour at each clinic or ward?",
     "questions": ["forecast patient visits per day", "predict emergency department arrivals",
                   "how many patients will we see next week", "forecast admissions for bed planning",
                   "predict clinic volume for staffing", "forecast daily hospital census"],
     "task": "regression", "time": "forecast", "primary_metric": "mae",
     "metric_why": "Staffing plans read the error as patients per shift; MAE is readable.",
     "unit": "clinic or ward per day (or hour)",
     "target_hint": [_x("visits|arrivals|patients|admissions|census|volume|encounters|patient_count"),
                     _w("visits|arrivals|admissions|census|patients")],
     "leakage_patterns": [_w(r"discharges_same\w*|lwbs|left_without\w*|actual_\w+")],
     "needed_columns": [_w("date|datetime|day|hour|ds"), _w("day_of_week|weekday|dow"), _w(r"holiday\w*"),
                        _w(r"flu\w*|season\w*|ili\w*"), _w(r"temp\w*|weather\w*"),
                        _w(r"clinic\w*|site\w*|ward\w*|department")],
     "families_prior": {**FORECAST}},
    # ---- manufacturing
    {"id": "predictive_maintenance", "name": "Predictive maintenance (failure in the next N days)",
     "domain": "manufacturing", "segments": [S, M, E], "question": "Which machines will fail in the next N days?",
     "questions": ["predict machine failures", "which machines will break down next week",
                   "predictive maintenance model from sensor data", "flag equipment likely to fail soon",
                   "predict failures in the next 30 days", "detect assets at risk of breakdown",
                   "when should we service each machine"],
     "task": "binary", "time": "time_split", "primary_metric": "f1_macro",
     "metric_why": "Failures are rare and a missed one is costly; f1_macro scores the maintenance flag instead "
                   "of a flattering AUC.",
     "unit": "machine per day (or cycle)",
     "target_hint": [_x(r"failure|machine_failure|failed|will_fail|fail|breakdown|failure_within_\w+|target"),
                     _w(r"fail\w*|breakdown\w*")],
     "leakage_patterns": [_w("twf|hdf|pwf|osf|rnf"),
                          _w(r"failure_(type|mode|code|date)|repair\w*|downtime\w*|maintenance_ticket\w*|"
                             r"replaced\w*|work_order\w*")],
     "needed_columns": [_w(r"temp\w*|temperature\w*|air_temperature\w*|process_temperature\w*"), _w(r"vibration\w*|vib\w*"),
                        _w(r"pressure\w*"), _w(r"rpm|rotational_speed\w*|speed"), _w(r"torque\w*|current\w*|voltage\w*|load"),
                        _w(r"tool_wear\w*|age\w*|hours\w*|cycles?"), _w(r"machine\w*|asset\w*|equipment\w*|model|type")],
     "families_prior": {"lightgbm": 1.2, "xgboost": 1.2, "random_forest": 1.1}},
    {"id": "remaining_useful_life", "name": "Remaining useful life", "domain": "manufacturing", "segments": [E],
     "question": "How many cycles or days does this asset have left before it fails?",
     "questions": ["predict remaining useful life", "how many cycles until the engine fails",
                   "estimate time to failure for each asset", "rul prediction from sensor readings",
                   "predict days until the next breakdown", "how long before this component wears out"],
     "task": "regression", "time": "time_split", "primary_metric": "rmse",
     "metric_why": "Large misses near end of life are the dangerous ones; RMSE (the NASA turbofan benchmark "
                   "metric) punishes them.",
     "unit": "asset per cycle",
     "target_hint": [_x("rul|remaining_useful_life|cycles_to_failure|time_to_failure|ttf|days_to_failure|remaining_life"),
                     _w(r"rul|remaining_\w+|time_to_failure|ttf")],
     "leakage_patterns": [_w(r"max_cycles?|total_cycles|end_of_life|failure_(cycle|date)|last_cycle")],
     "needed_columns": [_w(r"unit\w*|engine\w*|asset\w*|id"), _w(r"cycle\w*|time\w*|hours\w*"),
                        _w(r"sensor\w*|s\d+|measurement\w*"), _w(r"setting\w*|op_setting\w*|operating\w*")],
     "families_prior": {"lightgbm": 1.2, "xgboost": 1.1, "random_forest": 0.9}},
    {"id": "quality_defect", "name": "Quality defect prediction", "domain": "manufacturing", "segments": [S, M, E],
     "question": "Will this part, batch or product fail quality inspection?",
     "questions": ["predict defective parts", "flag products likely to fail quality inspection",
                   "which batches will be scrapped", "predict pass or fail from process data",
                   "quality prediction from machine settings", "detect defects before final inspection"],
     "task": "binary", "time": "time_split", "primary_metric": "f1_macro",
     "metric_why": "Defects are rare and the line acts on a pass or fail flag; f1_macro scores that flag.",
     "unit": "part or batch",
     "target_hint": [_x("defect|defective|is_defective|pass_fail|pass|fail|reject|rejected|scrap|quality|ok|nok"),
                     _x("label|target"), _w(r"defect\w*|reject\w*|scrap\w*")],
     "leakage_patterns": [_w(r"defect_(type|code|reason|count)|scrap_(reason|qty|cost)|rework\w*|"
                             r"inspection_(result|outcome|notes?)|qc_\w+|final_test\w*|returned\w*")],
     "needed_columns": [_w(r"temp\w*|temperature\w*"), _w(r"pressure\w*"), _w(r"speed\w*|rate\w*|feed\w*"),
                        _w(r"machine\w*|line\w*|station\w*|equipment\w*"), _w(r"material\w*|batch\w*|lot\w*|supplier\w*"),
                        _w(r"shift|operator\w*"), _w(r"duration\w*|cycle_time")],
     "families_prior": {"lightgbm": 1.2, "xgboost": 1.2, "random_forest": 1.1}},
    {"id": "yield_prediction", "name": "Process yield", "domain": "manufacturing", "segments": [M, E],
     "question": "What yield or output will this batch or production run achieve?",
     "questions": ["predict process yield per batch", "forecast production output for each run",
                   "what yield will we get from these settings", "predict throughput of the line",
                   "estimate batch yield from raw material properties", "predict crop or plant yield per field"],
     "task": "regression", "time": "time_split", "primary_metric": "rmse",
     "metric_why": "Yield sits in a narrow band and large shortfalls are what hurt; RMSE punishes them. Use mae "
                   "if a few bad batches are data errors.",
     "unit": "batch or production run",
     "target_hint": [_x("yield|yield_pct|yield_percent|yield_rate|output|throughput|production"),
                     _w(r"yield\w*|output\w*|throughput")],
     "leakage_patterns": [_w(r"good_units|scrap_(units|qty)|reject_(units|qty)|final_weight|output_weight|defects?_count")],
     "needed_columns": [_w(r"temp\w*|temperature\w*"), _w(r"pressure\w*"), _w(r"duration\w*|time\w*|cycle\w*"),
                        _w(r"material\w*|feed\w*|raw_\w+|purity\w*|moisture\w*"),
                        _w(r"equipment\w*|reactor\w*|line\w*|machine\w*"), _w(r"shift|operator\w*|batch\w*")],
     "families_prior": {"lightgbm": 1.2, "xgboost": 1.1}},
    {"id": "defect_type", "name": "Fault or defect type classification", "domain": "manufacturing",
     "segments": [E], "question": "Which kind of fault or defect is this?",
     "questions": ["classify the type of machine fault", "which failure mode caused the stop",
                   "predict defect category for each part", "diagnose the fault type from sensor readings",
                   "classify steel plate faults", "root cause category for each defect"],
     "task": "multiclass", "time": "none", "primary_metric": "f1_macro",
     "metric_why": "Some fault types are rare but matter as much as common ones; f1_macro weighs each class equally.",
     "unit": "defect event or part",
     "target_hint": [_x("defect_type|fault_type|failure_type|failure_mode|fault|fault_class|root_cause"),
                     _x("class|category"), _w(r"defect_type|fault\w*|failure_(type|mode)")],
     "leakage_patterns": [_w(r"repair_action\w*|corrective_action\w*|resolution\w*|technician_notes?")],
     "needed_columns": [_w(r"sensor\w*|measurement\w*|reading\w*"), _w(r"temp\w*|pressure\w*|vibration\w*|current\w*"),
                        _w(r"machine\w*|line\w*|station\w*"),
                        _w(r"x_\w+|y_\w+|area|perimeter|luminosity\w*|thickness\w*|length\w*")],
     "families_prior": {"lightgbm": 1.2, "xgboost": 1.1, "random_forest": 1.1}},
    {"id": "warranty_claim", "name": "Warranty claim prediction", "domain": "manufacturing", "segments": [M, E],
     "question": "Which sold units will come back with a warranty claim?",
     "questions": ["predict warranty claims", "which products will have a warranty claim",
                   "forecast warranty failures by build batch", "flag units likely to fail under warranty",
                   "predict returns under warranty for sold devices", "early warning for warranty issues"],
     "task": "binary", "time": "time_split", "primary_metric": "roc_auc",
     "metric_why": "Quality teams rank build batches and units for inspection; AUC.",
     "unit": "unit sold",
     "target_hint": [_x("warranty_claim|claimed|has_claim|claim|failed_in_warranty|returned"), _w(r"warranty\w*|claim\w*")],
     "leakage_patterns": [_w(r"claim_(date|amount|cost|code)|repair_(cost|date|code)\w*|failure_code\w*|"
                             r"replacement\w*|rma\w*")],
     "needed_columns": [_w(r"model\w*|product\w*|sku"), _w(r"plant\w*|factory\w*|line\w*"),
                        _w(r"build_date|manufactur\w*|production_date"), _w(r"supplier\w*|batch\w*|lot\w*|component\w*"),
                        _w(r"usage\w*|hours\w*|mileage"), _w("region|country|climate")],
     "families_prior": {"lightgbm": 1.2, "catboost": 1.1}},
]

# ---- text matching: TF-IDF over unigrams and bigrams, fit once on every phrasing
_STOP = frozenset(
    "a an the to of in on for and or is are be will would can could should i we our my me us you your it its "
    "this that these those with by from at as do does did which what who whom how when where whether want need "
    "like please help tell get going based using use model ml machine learning predict estimate each likely "
    "most more some any all there their them they have has under about into than then if so just also".split())
_IRREGULAR = {"left": "leave", "leaving": "leave", "bought": "buy", "buying": "buy", "sold": "sell", "paid": "pay",
              "fraudulent": "fraud", "fraudster": "fraud", "cancellation": "cancel", "cancelled": "cancel",
              "canceled": "cancel", "cancelling": "cancel", "canceling": "cancel", "conversion": "convert",
              "failure": "fail", "daily": "day", "renewal": "renew", "denial": "deny", "denied": "deny",
              "readmission": "readmit", "readmitted": "readmit", "delivery": "deliver", "monthly": "month",
              "weekly": "week", "yearly": "year", "annual": "year", "annually": "year", "quarterly": "quarter",
              "hourly": "hour", "shipping": "ship", "shipped": "ship", "shipment": "ship", "planning": "plan",
              "hiring": "hire", "hired": "hire", "defective": "defect", "quitting": "quit",
              "resignation": "resign", "subscription": "subscribe", "subscriber": "subscribe",
              "retention": "retain", "application": "apply", "applicant": "apply"}
_ENDINGS = (("ation", 3), ("ion", 4), ("ing", 4), ("ed", 4), ("ly", 3), ("e", 3))


def _stem(t: str) -> str:
    """Tiny deterministic stemmer: irregular map, plural strip, one derivational ending."""
    t = _IRREGULAR.get(t, t)
    if t.endswith("ies") and len(t) > 4:
        t = t[:-3] + "y"
    elif t.endswith("s") and len(t) > 3 and not t.endswith(("ss", "us", "is")):
        t = t[:-1]
    t = _IRREGULAR.get(t, t)
    for end, keep in _ENDINGS:
        if t.endswith(end) and len(t) - len(end) >= keep:
            return t[:-len(end)]
    return t


def _tokens(text: str) -> list[str]:
    out = []
    for raw in re.findall(r"[a-z0-9]+", text.lower()):
        if len(raw) < 2 or raw in _STOP:
            continue
        t = _stem(raw)
        if t not in _STOP:
            out.append(t)
    return out


_VEC = TfidfVectorizer(tokenizer=_tokens, token_pattern=None, lowercase=True, ngram_range=(1, 2), sublinear_tf=True)
_PHRASES = [(i, q) for i, u in enumerate(USE_CASES) for q in u["questions"]]
_P = _VEC.fit_transform([q for _, q in _PHRASES])
_DOCS = _VEC.transform([u["name"] + " " + " ".join(u["questions"]) for u in USE_CASES])

# ---- column matching
_NOT_TARGET = re.compile(r"(^|_)(lag|lead|rolling|roll|ewm|ewma|diff|shift|ma|mean|std|sum|min|max)_?\d"
                         r"|(^|_)(lag|rolling|ewm|shift)(_|$)|(^|_)(id|uuid|date|dt|at|timestamp)$")
_rx = lru_cache(maxsize=None)(re.compile)


def _snake(col: str) -> str:
    """SalePrice -> sale_price, 'No-show' -> no_show."""
    s = re.sub(r"(?<=[a-z0-9])(?=[A-Z])", "_", str(col))
    return re.sub(r"[^a-z0-9]+", "_", s.lower()).strip("_")


def _hits(patterns: list[str], names: list[str]) -> list[bool]:
    return [any(_rx(p).search(n) for p in patterns) for n in names]


def leakage_suspects(uc: dict, columns: list[str]) -> list[str]:
    """Columns whose names match the use case's leakage patterns (information from after the event)."""
    return [c for c, hit in zip(columns, _hits(uc["leakage_patterns"], [_snake(c) for c in columns])) if hit]


def suggest_target(uc: dict, columns: list[str]) -> str | None:
    """First column matching target_hint in pattern order, skipping leaks, ids, dates and lag features."""
    leaks = set(leakage_suspects(uc, columns))
    names = [(c, _snake(c)) for c in columns if c not in leaks]
    for p in uc["target_hint"]:
        for c, n in names:
            if not _NOT_TARGET.search(n) and _rx(p).search(n):
                return c
    return None


def _column_score(uc: dict, columns: list[str], names: list[str]) -> tuple[float, list[str]]:
    target = suggest_target(uc, columns)
    found = [c for c, hit in zip(columns, _hits(uc["needed_columns"], names)) if hit]
    covered = sum(any(_rx(p).search(n) for n in names) for p in uc["needed_columns"])
    reasons = ([f"target candidate column: {target}"] if target else []) + (
        [f"expected columns present: {', '.join(found[:6])}"] if found else [])
    return 0.6 * (target is not None) + 0.4 * covered / len(uc["needed_columns"]), reasons


def match(purpose: str, columns: list[str], task_hint: str | None = None, top_k: int = 3) -> list[dict]:
    """Rank use cases for a goal and dataset columns; each result is the entry plus score in [0, 1] and reasons.

    text = cosine blend scaled by sqrt(share of goal words known to the catalog vocabulary);
    score = (1 - COL_WEIGHT) * text + COL_WEIGHT * columns, halved when task_hint disagrees.
    task_hint: classification | regression | binary | multiclass | forecast | None.
    """
    if task_hint is not None and task_hint not in _HINT_KIND:
        raise ValueError(f"task_hint must be one of {sorted(_HINT_KIND)} or None, got {task_hint!r}")
    columns = [str(c) for c in columns or []]
    names = [_snake(c) for c in columns]
    toks = _tokens(purpose or "")
    coverage = sum(t in _VEC.vocabulary_ for t in toks) / len(toks) if toks else 0.0
    q = _VEC.transform([purpose or ""])
    phrase_sims = (_P @ q.T).toarray().ravel()
    doc_sims = (_DOCS @ q.T).toarray().ravel()
    best = np.zeros(len(USE_CASES))
    best_q = [""] * len(USE_CASES)
    for (i, text), s in zip(_PHRASES, phrase_sims):
        if s > best[i]:
            best[i], best_q[i] = s, text
    out = []
    for i, uc in enumerate(USE_CASES):
        # unknown words vanish from the tf-idf vector; scale down so one known word cannot look like a match
        text = (BEST_PHRASE * best[i] + (1 - BEST_PHRASE) * doc_sims[i]) * coverage ** 0.5
        col, reasons = _column_score(uc, columns, names)
        score = (1 - COL_WEIGHT) * text + COL_WEIGHT * col
        if best_q[i]:
            reasons = [f'goal resembles "{best_q[i]}" (similarity {best[i]:.2f})'] + reasons
        if task_hint and _HINT_KIND[task_hint] != TASK_KIND[uc["task"]]:
            score *= TASK_MISMATCH
            reasons.append(f"task hint {task_hint} does not fit {uc['task']}")
        out.append({**uc, "score": round(float(min(max(score, 0.0), 1.0)), 4),
                    "reasons": reasons or ["no overlap with the goal or the columns"]})
    return sorted(out, key=lambda m: (-m["score"], m["id"]))[:max(top_k, 0)]
